name: legalmetro_scan
description: LegalMetro Scan — Legal Metrology label compliance checker (mobile).
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.0.0
  camera: ^0.11.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
